const channels = [
  {
    name: "BBC One",
    programs: [
      { name: "Midnight News", startTime: "12:00 AM", duration: 60 },
      { name: "Late Night Talk", startTime: "01:00 AM", duration: 120 },
      { name: "World Stories", startTime: "03:30 AM", duration: 90 },
      { name: "Morning News", startTime: "06:00 AM", duration: 60 },
      { name: "Breakfast Show", startTime: "07:30 AM", duration: 90 },
      { name: "Cooking Masterclass", startTime: "09:15 AM", duration: 35 },
      { name: "Drama Series", startTime: "10:00 AM", duration: 120 },
      { name: "Lunch News", startTime: "12:15 PM", duration: 30 },
      { name: "Afternoon Documentary", startTime: "02:00 PM", duration: 90 },
      { name: "Evening News", startTime: "06:00 PM", duration: 60 },
      { name: "Prime Time Movie", startTime: "07:30 PM", duration: 120 },
      { name: "Late Night Comedy", startTime: "10:00 PM", duration: 120 },
    ],
  },
  {
    name: "CNN",
    programs: [
      { name: "World Report", startTime: "12:30 AM", duration: 45 },
      { name: "Midnight Highlights", startTime: "01:30 AM", duration: 75 },
      { name: "Tech Roundup", startTime: "03:00 AM", duration: 60 },
      { name: "World News", startTime: "06:00 AM", duration: 45 },
      { name: "Market Update", startTime: "06:45 AM", duration: 75 },
      { name: "Tech Today", startTime: "08:30 AM", duration: 60 },
      { name: "Midday Report", startTime: "12:00 PM", duration: 90 },
      { name: "Breaking News", startTime: "02:30 PM", duration: 60 },
      { name: "Evening Highlights", startTime: "05:00 PM", duration: 90 },
      { name: "Political Panel", startTime: "08:00 PM", duration: 120 },
      { name: "Nightly News", startTime: "11:00 PM", duration: 60 },
    ],
  },
  {
    name: "ESPN",
    programs: [
      { name: "Midnight Recap", startTime: "12:00 AM", duration: 90 },
      { name: "Late Night Soccer", startTime: "01:30 AM", duration: 120 },
      { name: "Basketball Highlights", startTime: "04:00 AM", duration: 60 },
      { name: "Morning Sports Recap", startTime: "06:00 AM", duration: 60 },
      { name: "Live Soccer Match", startTime: "07:00 AM", duration: 120 },
      { name: "Cricket Highlights", startTime: "11:00 AM", duration: 45 },
      { name: "Tennis Grand Slam", startTime: "11:45 AM", duration: 75 },
      { name: "Afternoon Show", startTime: "03:00 PM", duration: 120 },
      { name: "Evening Sports Roundup", startTime: "07:00 PM", duration: 90 },
      { name: "Late Night Boxing", startTime: "10:30 PM", duration: 90 },
    ],
  },
  {
    name: "Discovery Channel",
    programs: [
      { name: "Deep Sea Exploration", startTime: "12:00 AM", duration: 120 },
      { name: "Animal Adventures", startTime: "02:30 AM", duration: 90 },
      { name: "Morning Safari", startTime: "06:00 AM", duration: 60 },
      { name: "Science Mysteries", startTime: "07:30 AM", duration: 60 },
      { name: "Planet Earth", startTime: "08:30 AM", duration: 120 },
      { name: "Historical Wonders", startTime: "10:30 AM", duration: 90 },
      { name: "Technology Trends", startTime: "01:00 PM", duration: 60 },
      { name: "Exploration Hour", startTime: "04:00 PM", duration: 90 },
      { name: "Evening Specials", startTime: "06:30 PM", duration: 120 },
      { name: "Night at the Museum", startTime: "10:30 PM", duration: 120 },
    ],
  },
  {
    name: "Cartoon Network",
    programs: [
      { name: "Midnight Classics", startTime: "12:00 AM", duration: 60 },
      { name: "Adventure Time", startTime: "01:30 AM", duration: 60 },
      { name: "Morning Cartoons", startTime: "06:00 AM", duration: 60 },
      { name: "Adventure Hour", startTime: "07:00 AM", duration: 60 },
      { name: "Classic Cartoons", startTime: "08:30 AM", duration: 90 },
      { name: "Lunchtime Laughs", startTime: "12:00 PM", duration: 60 },
      { name: "Afternoon Giggles", startTime: "02:00 PM", duration: 90 },
      { name: "Evening Animation", startTime: "05:00 PM", duration: 120 },
      { name: "Family Fun Night", startTime: "07:30 PM", duration: 90 },
      { name: "Late Night Giggles", startTime: "10:00 PM", duration: 120 },
    ],
  },
];

export { channels };
