const channels = [
  {
    name: "BBC One",
    programs: [
      { name: "Morning News", time: "06:00 AM" },
      { name: "Breakfast Show", time: "07:00 AM" },
      { name: "Cooking Masterclass", time: "09:00 AM" },
      { name: "Drama Series", time: "11:00 AM" },
      { name: "Lunch News", time: "01:00 PM" },
      { name: "Afternoon Documentary", time: "02:00 PM" },
      { name: "Evening Show", time: "06:00 PM" },
      { name: "Prime Time Movie", time: "08:00 PM" },
      { name: "Late Night Talk Show", time: "10:00 PM" },
    ],
  },
  {
    name: "CNN",
    programs: [
      { name: "World News", time: "06:00 AM" },
      { name: "Market Update", time: "07:30 AM" },
      { name: "Tech Today", time: "09:00 AM" },
      { name: "Midday Report", time: "12:00 PM" },
      { name: "Sports Highlights", time: "03:00 PM" },
      { name: "Evening News", time: "06:00 PM" },
      { name: "Political Panel", time: "08:00 PM" },
      { name: "World Affairs", time: "09:30 PM" },
    ],
  },
  {
    name: "ESPN",
    programs: [
      { name: "Morning Sports Recap", time: "06:00 AM" },
      { name: "Live Soccer Match", time: "08:00 AM" },
      { name: "Cricket Highlights", time: "11:00 AM" },
      { name: "Tennis Grand Slam", time: "02:00 PM" },
      { name: "Evening Sports Roundup", time: "06:00 PM" },
      { name: "Live Basketball", time: "07:30 PM" },
      { name: "Late Night Boxing", time: "10:00 PM" },
    ],
  },
  {
    name: "Discovery Channel",
    programs: [
      { name: "Animal Adventures", time: "06:00 AM" },
      { name: "Science Mysteries", time: "08:00 AM" },
      { name: "Planet Earth", time: "10:00 AM" },
      { name: "Historical Wonders", time: "01:00 PM" },
      { name: "Technology Trends", time: "03:00 PM" },
      { name: "Wildlife Specials", time: "05:00 PM" },
      { name: "Exploration Hour", time: "08:00 PM" },
      { name: "Night at the Museum", time: "10:00 PM" },
    ],
  },
  {
    name: "Cartoon Network",
    programs: [
      { name: "Morning Cartoons", time: "06:00 AM" },
      { name: "Adventure Hour", time: "08:00 AM" },
      { name: "Classic Cartoons", time: "10:00 AM" },
      { name: "Lunchtime Laughs", time: "12:00 PM" },
      { name: "Afternoon Action", time: "02:00 PM" },
      { name: "Evening Animation", time: "05:00 PM" },
      { name: "Family Fun", time: "07:00 PM" },
      { name: "Late Night Giggles", time: "09:00 PM" },
    ],
  },
  {
    name: "BBC One",
    programs: [
      { name: "Morning News", time: "06:00 AM" },
      { name: "Breakfast Show", time: "07:00 AM" },
      { name: "Cooking Masterclass", time: "09:00 AM" },
      { name: "Drama Series", time: "11:00 AM" },
      { name: "Lunch News", time: "01:00 PM" },
      { name: "Afternoon Documentary", time: "02:00 PM" },
      { name: "Evening Show", time: "06:00 PM" },
      { name: "Prime Time Movie", time: "08:00 PM" },
      { name: "Late Night Talk Show", time: "10:00 PM" },
    ],
  },
  {
    name: "CNN",
    programs: [
      { name: "World News", time: "06:00 AM" },
      { name: "Market Update", time: "07:30 AM" },
      { name: "Tech Today", time: "09:00 AM" },
      { name: "Midday Report", time: "12:00 PM" },
      { name: "Sports Highlights", time: "03:00 PM" },
      { name: "Evening News", time: "06:00 PM" },
      { name: "Political Panel", time: "08:00 PM" },
      { name: "World Affairs", time: "09:30 PM" },
    ],
  },
  {
    name: "ESPN",
    programs: [
      { name: "Morning Sports Recap", time: "06:00 AM" },
      { name: "Live Soccer Match", time: "08:00 AM" },
      { name: "Cricket Highlights", time: "11:00 AM" },
      { name: "Tennis Grand Slam", time: "02:00 PM" },
      { name: "Evening Sports Roundup", time: "06:00 PM" },
      { name: "Live Basketball", time: "07:30 PM" },
      { name: "Late Night Boxing", time: "10:00 PM" },
    ],
  },
  {
    name: "Discovery Channel",
    programs: [
      { name: "Animal Adventures", time: "06:00 AM" },
      { name: "Science Mysteries", time: "08:00 AM" },
      { name: "Planet Earth", time: "10:00 AM" },
      { name: "Historical Wonders", time: "01:00 PM" },
      { name: "Technology Trends", time: "03:00 PM" },
      { name: "Wildlife Specials", time: "05:00 PM" },
      { name: "Exploration Hour", time: "08:00 PM" },
      { name: "Night at the Museum", time: "10:00 PM" },
    ],
  },
  {
    name: "Cartoon Network",
    programs: [
      { name: "Morning Cartoons", time: "06:00 AM" },
      { name: "Adventure Hour", time: "08:00 AM" },
      { name: "Classic Cartoons", time: "10:00 AM" },
      { name: "Lunchtime Laughs", time: "12:00 PM" },
      { name: "Afternoon Action", time: "02:00 PM" },
      { name: "Evening Animation", time: "05:00 PM" },
      { name: "Family Fun", time: "07:00 PM" },
      { name: "Late Night Giggles", time: "09:00 PM" },
    ],
  },
  {
    name: "BBC One",
    programs: [
      { name: "Morning News", time: "06:00 AM" },
      { name: "Breakfast Show", time: "07:00 AM" },
      { name: "Cooking Masterclass", time: "09:00 AM" },
      { name: "Drama Series", time: "11:00 AM" },
      { name: "Lunch News", time: "01:00 PM" },
      { name: "Afternoon Documentary", time: "02:00 PM" },
      { name: "Evening Show", time: "06:00 PM" },
      { name: "Prime Time Movie", time: "08:00 PM" },
      { name: "Late Night Talk Show", time: "10:00 PM" },
    ],
  },
  {
    name: "CNN",
    programs: [
      { name: "World News", time: "06:00 AM" },
      { name: "Market Update", time: "07:30 AM" },
      { name: "Tech Today", time: "09:00 AM" },
      { name: "Midday Report", time: "12:00 PM" },
      { name: "Sports Highlights", time: "03:00 PM" },
      { name: "Evening News", time: "06:00 PM" },
      { name: "Political Panel", time: "08:00 PM" },
      { name: "World Affairs", time: "09:30 PM" },
    ],
  },
  {
    name: "ESPN",
    programs: [
      { name: "Morning Sports Recap", time: "06:00 AM" },
      { name: "Live Soccer Match", time: "08:00 AM" },
      { name: "Cricket Highlights", time: "11:00 AM" },
      { name: "Tennis Grand Slam", time: "02:00 PM" },
      { name: "Evening Sports Roundup", time: "06:00 PM" },
      { name: "Live Basketball", time: "07:30 PM" },
      { name: "Late Night Boxing", time: "10:00 PM" },
    ],
  },
  {
    name: "Discovery Channel",
    programs: [
      { name: "Animal Adventures", time: "06:00 AM" },
      { name: "Science Mysteries", time: "08:00 AM" },
      { name: "Planet Earth", time: "10:00 AM" },
      { name: "Historical Wonders", time: "01:00 PM" },
      { name: "Technology Trends", time: "03:00 PM" },
      { name: "Wildlife Specials", time: "05:00 PM" },
      { name: "Exploration Hour", time: "08:00 PM" },
      { name: "Night at the Museum", time: "10:00 PM" },
    ],
  },
  {
    name: "Cartoon Network",
    programs: [
      { name: "Morning Cartoons", time: "06:00 AM" },
      { name: "Adventure Hour", time: "08:00 AM" },
      { name: "Classic Cartoons", time: "10:00 AM" },
      { name: "Lunchtime Laughs", time: "12:00 PM" },
      { name: "Afternoon Action", time: "02:00 PM" },
      { name: "Evening Animation", time: "05:00 PM" },
      { name: "Family Fun", time: "07:00 PM" },
      { name: "Late Night Giggles", time: "09:00 PM" },
    ],
  },
];


export {channels}